# Target Guided Ordinal Encoding

### Techniques used to encode categorical variable based on their relationship with the target variables. This techniques is useful if we have categorical variable with a large numbr of unique categories, and we want to use this variable as feature in our machine learning model.

#### Here, we replace the category in the categorical variable with a numerical value based on the mean or median of the target variable for that category.

In [1]:
import pandas as pd

df = pd.DataFrame({
    'city':['new york', 'London', 'Paris', 'Tokyo', 'new york', 'Paris'],
    'price': [200,150, 300, 250, 180, 320]
})

In [2]:
df

       city  price
0  new york    200
1    London    150
2     Paris    300
3     Tokyo    250
4  new york    180
5     Paris    320

#### mathi NewYork ma 200 and 180 xa so to replace new york with a categorical values, we can replace it by mean of 200 and 180

In [6]:
mean_price = df.groupby('city')['price'].mean()

In [7]:
mean_price

city
London      150.0
Paris       310.0
Tokyo       250.0
new york    190.0
Name: price, dtype: float64

In [8]:
mean_price.to_dict()

{'London': 150.0, 'Paris': 310.0, 'Tokyo': 250.0, 'new york': 190.0}

In [9]:
df['city_encoded'] = df['city'].map(mean_price)

In [11]:
df

       city  price  city_encoded
0  new york    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  new york    180         190.0
5     Paris    320         310.0

In [17]:
df[['city_encoded', 'price']]

   city_encoded  price
0         190.0    200
1         150.0    150
2         310.0    300
3         250.0    250
4         190.0    180
5         310.0    320

In [ ]:
#### Assignment : target guided encoding of time based on total_bill
import seaborn as sns
data = sns.load_dataset('tips')
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [24]:
dataa = pd.concat([data['time'], data['total_bill']], axis = 1)

In [25]:
dataa

       time  total_bill
0    Dinner       16.99
1    Dinner       10.34
2    Dinner       21.01
3    Dinner       23.68
4    Dinner       24.59
..      ...         ...
239  Dinner       29.03
240  Dinner       27.18
241  Dinner       22.67
242  Dinner       17.82
243  Dinner       18.78

[244 rows x 2 columns]

In [26]:
mean_bill = dataa.groupby('time')['total_bill'].mean().to_dict()

/tmp/ipykernel_24219/653802919.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_bill = dataa.groupby('time')['total_bill'].mean().to_dict()

In [27]:
mean_bill

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [32]:
dataa['time_encoded']=dataa['time'].map(mean_bill)

In [33]:
dataa

       time  total_bill time_encoded
0    Dinner       16.99    20.797159
1    Dinner       10.34    20.797159
2    Dinner       21.01    20.797159
3    Dinner       23.68    20.797159
4    Dinner       24.59    20.797159
..      ...         ...          ...
239  Dinner       29.03    20.797159
240  Dinner       27.18    20.797159
241  Dinner       22.67    20.797159
242  Dinner       17.82    20.797159
243  Dinner       18.78    20.797159

[244 rows x 3 columns]

In [35]:
dataa[['time_encoded', 'total_bill']]

    time_encoded  total_bill
0      20.797159       16.99
1      20.797159       10.34
2      20.797159       21.01
3      20.797159       23.68
4      20.797159       24.59
..           ...         ...
239    20.797159       29.03
240    20.797159       27.18
241    20.797159       22.67
242    20.797159       17.82
243    20.797159       18.78

[244 rows x 2 columns]