# Pandas - DataFrame and Series

### Powerful data manupulation library in Python, widely used for data analusis and data cleaning. It provides two primary data structures: Series and DataFrame. A series is one-dimensional array-like object, while Dataframe is two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labelled axes (rows and columns)

In [3]:
! pip install pandas

Requirement already satisfied: pandas in /home/prashant/practice/venv/lib/python3.12/site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in /home/prashant/practice/venv/lib/python3.12/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/prashant/practice/venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/prashant/practice/venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### Series

In [ ]:

# 1-D array like object that can hold any data type. It is similar to column in a table.
# creating series from list
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [7]:
# creating series from dictionary
data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)
print(type(series_dict))

a    1
b    2
c    3
dtype: int64
<class 'pandas.Series'>

In [11]:
# index manupulation in Series
data = [1,3,5,7]
index = ['a','c','e', 'g']
pd.Series(data, index = index)

a    1
c    3
e    5
g    7
dtype: int64

### DataFrame

In [15]:
# 2-D similar to a table in database
## creating a DataFrame form a dictionary of list

data = {
    'name': ['prashant', 'john', 'jack'],
    'age' : [23,44,35],
    'city' : ['bangalore','delhi','patna']
}

df = pd.DataFrame(data)
print(df)
print('\n')
print(type(df))

       name  age       city
0  prashant   23  bangalore
1      john   44      delhi
2      jack   35      patna


<class 'pandas.DataFrame'>

In [17]:
import numpy as np
print(np.array(data))

{'name': ['prashant', 'john', 'jack'], 'age': [23, 44, 35], 'city': ['bangalore', 'delhi', 'patna']}

In [24]:
# create a data frame from a list of dictionaries

data = [
    {'name':'prashant', 'age': 32, 'city': 'Bangalore'},
    {'name':'john', 'age': 32, 'city': 'Bangalore'},
    {'name':'jack', 'age': 32, 'city': 'Bangalore'},
    {'name':'khoi', 'age': 32, 'city': 'Bangalore'},
]

df = pd.DataFrame(data)
print(df)

       name  age       city
0  prashant   32  Bangalore
1      john   32  Bangalore
2      jack   32  Bangalore
3      khoi   32  Bangalore

In [26]:
df.iat[2,2]

'Bangalore'

In [27]:
df.head()

       name  age       city
0  prashant   32  Bangalore
1      john   32  Bangalore
2      jack   32  Bangalore
3      khoi   32  Bangalore

In [ ]:
# accessing a specified element using at and iat
print(df.at[2,'age'])

32

In [31]:
print(df.iat[2,2])

Bangalore

In [33]:
# data manupulation with DataFrame
df

       name  age       city
0  prashant   32  Bangalore
1      john   32  Bangalore
2      jack   32  Bangalore
3      khoi   32  Bangalore

In [35]:
# adding new column

df['sarary'] = [100000,40000,20000,1000]
df

       name  age       city  sarary
0  prashant   32  Bangalore  100000
1      john   32  Bangalore   40000
2      jack   32  Bangalore   20000
3      khoi   32  Bangalore    1000

In [43]:
# removing a column

df.drop('sarary', axis = 1, inplace = True)

In [44]:
df

       name  age       city
0  prashant   32  Bangalore
1      john   32  Bangalore
2      jack   32  Bangalore
3      khoi   32  Bangalore

In [45]:
# increasing the age
df['age'] = df['age']+1
df

       name  age       city
0  prashant   33  Bangalore
1      john   33  Bangalore
2      jack   33  Bangalore
3      khoi   33  Bangalore

In [46]:
df['city'] = 'us'

In [47]:
df

       name  age city
0  prashant   33   us
1      john   33   us
2      jack   33   us
3      khoi   33   us

In [48]:
df.drop(3, inplace = True)

In [49]:
df

       name  age city
0  prashant   33   us
1      john   33   us
2      jack   33   us

In [ ]:
df.read_csv('naam haalni yaha')

In [ ]:
df.describe() # gives statistical summary

        age
count   3.0
mean   33.0
std     0.0
min    33.0
25%    33.0
50%    33.0
75%    33.0
max    33.0