In [13]:
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
data = sns.load_dataset('tips')

In [14]:
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
df = pd.DataFrame(data)

In [16]:
encoder = OneHotEncoder()

In [28]:
encoded1 = encoder.fit_transform(df[['sex']]).toarray()

In [29]:
encoded2 = encoder.fit_transform(df[['smoker']]).toarray()

In [30]:
sex_encoded = pd.DataFrame(encoded1, columns = encoder.get_feature_names_out())
smoker_encoded = pd.DataFrame(encoded2, columns = encoder.get_feature_names_out())

In [31]:
pd.concat([sex_encoded, smoker_encoded], axis = 1)

     smoker_No  smoker_Yes  smoker_No  smoker_Yes
0          1.0         0.0        1.0         0.0
1          0.0         1.0        1.0         0.0
2          0.0         1.0        1.0         0.0
3          0.0         1.0        1.0         0.0
4          1.0         0.0        1.0         0.0
..         ...         ...        ...         ...
239        0.0         1.0        1.0         0.0
240        1.0         0.0        0.0         1.0
241        0.0         1.0        0.0         1.0
242        0.0         1.0        1.0         0.0
243        1.0         0.0        1.0         0.0

[244 rows x 4 columns]

In [32]:
pd.concat([sex_encoded, smoker_encoded])

     smoker_No  smoker_Yes
0          1.0         0.0
1          0.0         1.0
2          0.0         1.0
3          0.0         1.0
4          1.0         0.0
..         ...         ...
239        1.0         0.0
240        0.0         1.0
241        0.0         1.0
242        1.0         0.0
243        1.0         0.0

[488 rows x 2 columns]

In [34]:
df['sex']

0      Female
1        Male
2        Male
3        Male
4      Female
        ...
239      Male
240    Female
241      Male
242      Male
243    Female
Name: sex, Length: 244, dtype: category
Categories (2, object): ['Male', 'Female']