## Encoding means converting categorical features into some numerical values so that the model can understand for some particualar operations.  [sequence of 0s and 1s]

# Data Encoding
### 1. Nominal/ OHE Encoding   
### 2. Label and Ordinal Encoding    
### 3. Target Guided Ordinal Encoding

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
# create a simple DataFrame
df = pd.DataFrame({
    'color' : ['red','blue','green','yellow','red','blue']
})

In [5]:
df.head()

    color
0     red
1    blue
2   green
3  yellow
4     red

In [6]:
# create an instance of OneHotEncoder
encoder = OneHotEncoder()

In [44]:
# perform fit and then transform
encoded = encoder.fit_transform(df[['color']]).toarray()

In [45]:
encoded_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [ ]:
encoded_df

   color_blue  color_green  color_red  color_yellow
0         0.0          0.0        1.0           0.0
1         1.0          0.0        0.0           0.0
2         0.0          1.0        0.0           0.0
3         0.0          0.0        0.0           1.0
4         0.0          0.0        1.0           0.0
5         1.0          0.0        0.0           0.0

In [15]:
# for new data
encoder.transform([['blue']]).toarray()

/home/prashant/practice/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0., 0.]])

In [16]:
pd.concat([df, encoded_df], axis = 1)

    color  color_blue  color_green  color_red  color_yellow
0     red         0.0          0.0        1.0           0.0
1    blue         1.0          0.0        0.0           0.0
2   green         0.0          1.0        0.0           0.0
3  yellow         0.0          0.0        0.0           1.0
4     red         0.0          0.0        1.0           0.0
5    blue         1.0          0.0        0.0           0.0

In [19]:
# assignment
import seaborn as sns
data = sns.load_dataset('tips')

In [20]:
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [25]:
cat_col = data[['sex']]

In [26]:
cat_col.head()

      sex
0  Female
1    Male
2    Male
3    Male
4  Female

In [39]:
encoded1 = encoder.fit_transform(cat_col).toarray()

In [40]:
encoded2 = encoder.fit_transform(data[['smoker']]).toarray()

In [46]:
encoded_df1 = pd.DataFrame(encoded1, columns = encoder.get_feature_names_out())

ValueError: Shape of passed values is (244, 2), indices imply (244, 4)

In [38]:
pd.concat([sex_encoded, smoker_encoded], axis = 1)

TypeError: cannot concatenate object of type '<class 'numpy.ndarray'>'; only Series and DataFrame objs are valid